AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  a-new-startup : Sets up the DynamoDB database, SNS Topic, SQS Queue, SSM parameters and some IAM things for a-new-startup"
#
# The resources created here will have dynamic and unique names.
# If you want static names for a local build - use template-static-names.yaml instead.
#

Parameters:

  Prefix:
    Type: String
    Default: "a-new-startup"
    Description: "Used for the unique naming of resources and exports.  You probably should not change this."

  Environment:
    Type: String
    Default: dev
    Description: "Environment name for the SSM parameters created."
    
Resources:

  StartupSignupsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # No TableName specified, a dynamic name will be generated.
      BillingMode: 'PAY_PER_REQUEST'
      AttributeDefinitions:
        -
          AttributeName: email
          AttributeType: S
      KeySchema:
        - 
          AttributeName: email
          KeyType: HASH 
      Tags:
        - Key: demo
          Value: a-new-startup

      
  NewSignupQueue: 
    Type: AWS::SQS::Queue
    Properties:
      Tags:
        - Key: demo
          Value: a-new-startup

  NewSignupTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint:
          Fn::GetAtt: [NewSignupQueue, Arn]
        Protocol: sqs
      Tags:
        - Key: demo
          Value: a-new-startup

  AllowSNS2SQSPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Id: PublicationPolicy
        Statement:
        - Action: ['sqs:SendMessage']
          Condition:
            ArnEquals:
              aws:SourceArn: {Ref: NewSignupTopic}
          Effect: Allow
          Principal: {AWS: '*'}
          Resource:
            Fn::GetAtt: [NewSignupQueue, Arn]
          Sid: Allow-SNS-SendMessage
        Version: '2012-10-17'
      Queues:
      - {Ref: NewSignupQueue}
  
  #
  # NOTE: The following are referenced by the scripts/start_server script.
  # When running running on EC2, the CodeDeploy agent will execute that as a hook.
  # These have the "ENVIRONMENT" embedded in them - here it's dev (for development)
  # If you wanted to extend for there to be a qa environment you'd have to make changes here.
  #
  # These can also be referenced when creating a container image - to set as appropriate the
  # Environment variables of the container image
  # See build_container as an example
  #
  # However, when running in ECS or EKS, we use the facilities of those orchestrators to set the environment variables
  # (For ECS in the "Task Definiton" and for EKS in the Deployment / podspec)
  #
  
  SSMParamAccount:
    Type: AWS::SSM::Parameter
    Properties:
      Name: 
        !Sub
          - '/${Param}'
          - Param: !Join
            - '/'
            - - !Ref Prefix
              - !Ref Environment
              - "aws-account"
      Type: String
      Value: !Ref AWS::AccountId
      Tags:
        demo: a-new-startup

  SSMParamTable:
    Type: AWS::SSM::Parameter
    Properties:
      Name: 
        !Sub
          - '/${Param}'
          - Param: !Join
            - '/'
            - - !Ref Prefix
              - !Ref Environment
              - "tablename"
      Type: String
      Value: !Ref StartupSignupsTable
      Tags:
        demo: a-new-startup

  SSMParamTopic:
    Type: AWS::SSM::Parameter
    Properties:
      Name:
        !Sub
          - '/${Param}'
          - Param: !Join
            - '/'
            - - !Ref Prefix
              - !Ref Environment
              - "topicarn"
      Type: String
      Value: !Ref NewSignupTopic
      Tags:
        demo: a-new-startup

  #
  # This is an OPTIONAL custom metric configuration (memory used)
  # You'll need to run 08-configure-cloudwatch.sh AFTER installing...
  # See that sh for details.
  #
  SSMCloudWatchAgentConfig:
    Type: AWS::SSM::Parameter
    Properties:
      Name:
        !Sub
          - '/${Param}'
          - Param: !Join
            - '/'
            - - !Ref Prefix
              - !Ref Environment
              - "AmazonCloudWatch-AgentConfig"
      Type: String
      # See: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-Configuration-File-Details.html
      Value: |
        {
          "agent": {
            "metrics_collection_interval": 15,
            "run_as_user": "root"
          },
          "metrics": {
            "namespace": "A-New-Startup",
            "append_dimensions": {
              "AutoScalingGroupName": "${!aws:AutoScalingGroupName}",
              "ImageId": "${!aws:ImageId}",
              "InstanceId": "${!aws:InstanceId}",
              "InstanceType": "${!aws:InstanceType}"
            },
            "metrics_collected": {
              "netstat": {
                "measurement": [
                  "tcp_established",
                  "tcp_syn_sent",
                  "tcp_close"
                ],
                "metrics_collection_interval": 60
              },
              "mem": {
                "measurement": [
                  "mem_used_percent"
                ],
                "metrics_collection_interval": 15
              },
              "disk": {
                "measurement": [
                  "used_percent"
                ],
                "resources": [
                  "*"
                ],
                "drop_device": true
              },
              "processes": {
                "measurement": [
                  "running",
                  "sleeping",
                  "dead"
                ]
              }
            }
          }
        }

      Tags:
        demo: a-new-startup

  AppManagedPolicy:
      Type: AWS::IAM::ManagedPolicy
      # Basic application level permissions needed for a-new-startup to run.
      Properties:
        # No PolicyName used, we want a unique name generated automatically
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:PutItem'
              Resource:
                - Fn::Join:
                    - ""
                    - - "arn:"
                      - Ref: AWS::Partition
                      - ":dynamodb:"
                      - Ref: AWS::Region
                      - ":"
                      - Ref: AWS::AccountId
                      # Note how we use wildcards.  The backend resource names must start with a-new-startup
                      - :table/a-new-startup*
            - Effect: Allow
              Action:
                - 'ssm:GetParameter*'
              Resource:
                - Fn::Join:
                    - ""
                    - - "arn:"
                      - Ref: AWS::Partition
                      - ":ssm:"
                      - Ref: AWS::Region
                      - ":"
                      - Ref: AWS::AccountId
                      - :parameter/a-new-startup*
            - Effect: Allow
              Action:
                - 'sns:Publish'
              Resource:
                - Fn::Join:
                    - ""
                    - - "arn:"
                      - Ref: AWS::Partition
                      - ":sns:"
                      - Ref: AWS::Region
                      - ":"
                      - Ref: AWS::AccountId
                      - :a-new-startup*
            # If using X-Ray, the Daemon will need these permissions to upload data to cloud.
            - Effect: Allow
              Action: 
                - "xray:PutTraceSegments"
                - "xray:PutTelemetryRecords"
                - "xray:GetSamplingRules"
                - "xray:GetSamplingTargets"
                - "xray:GetSamplingStatisticSummaries"
              Resource: "*"
            # The ec2 instance will need to be able to download the bundle (CodeDeploy)
            # This requires the build to be in a bucket that starts with a-new-startup*
            - Effect: Allow
              Action:
                - 's3:Get*'
                - 's3:List*'
              Resource:
                - Fn::Join:
                    - ""
                    - - "arn:"
                      - Ref: AWS::Partition
                      - ":s3"
                      - ":"
                      - ":"
                      - ":a-new-startup*"
                - Fn::Join:
                    - ""
                    - - "arn:"
                      - Ref: AWS::Partition
                      - ":s3"
                      - ":"
                      - ":"
                      - ":a-new-startup*/*"
                # In case you are using the default codepipeline artifact bucket...
                # (sometimes in manual demos I do this)
                - Fn::Join:
                    - ""
                    - - "arn:"
                      - Ref: AWS::Partition
                      - ":s3"
                      - ":"
                      - ":"
                      - ":codepipline-*/*"

Outputs:

  # Using the technique of chained stacks, other CFN stacks will need these values.

  TableName:
    Value: !Ref StartupSignupsTable
    Export:
      Name: !Join ['-', [!Ref Prefix, 'TableName']]
      
  TopicArn:
    Value: !Ref NewSignupTopic
    Export:
      Name: !Join ['-', [!Ref Prefix, 'TopicArn']]

  QueueArn:
    Value: !GetAtt NewSignupQueue.Arn
    Export:
      Name: !Join ['-', [!Ref Prefix, 'QueueArn']]

  AppManagedPolicy:
    Value: !Ref AppManagedPolicy
    Export:
      Name: !Join ['-', [!Ref Prefix, 'AppManagedPolicy']]