AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  a-new-startup : Sets up the Build Projects, Artifact bucket, and other things needed by the CI/CD Pipeline


Parameters:
  Prefix:
    Type: String
    Default: "a-new-startup"
    Description: "Used for the unique naming of resources and exports.  You probably should not change this."

Resources:
  
#
#  ____  ____ 
# / ___)( __ \
# \___ \ (__ (
# (____/(____/
#

  # CodePipeline will use this for Artifacts
  ArtifactStoreBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      Tags:
        - Key: demo
          Value: a-new-startup


#
#  ___  __  ____  ____  ____  _  _  __  __    ____ 
# / __)/  \(    \(  __)(  _ \/ )( \(  )(  )  (    \
#( (__(  O )) D ( ) _)  ) _ () \/ ( )( / (_/\ ) D (
# \___)\__/(____/(____)(____/\____/(__)\____/(____/
#

  # This project builds the application code (NodeJS) 
  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
        Name: a-new-startup-build
        Artifacts:
            Type: CODEPIPELINE
        Environment:
            ComputeType: BUILD_GENERAL1_SMALL
            # Ubuntu with NodeJS 18
            Image: aws/codebuild/standard:7.0
            PrivilegedMode: false
            Type: LINUX_CONTAINER
            EnvironmentVariables:
            - Name: BUCKET_NAME
              Type: PLAINTEXT
              Value: !Ref ArtifactStoreBucket
        ServiceRole:
            Fn::GetAtt:
            - BuildRole
            - Arn
        Source:
            # Assume buildspec.yaml is in the source root directory
            Type: CODEPIPELINE
        Tags:
          - Key: demo
            Value: a-new-startup


  # This project is used to build a Container Image of the testing code (Python/Selenium)
  TestImageBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
        Name: a-new-startup-test-image-build
        Tags:
        - Key: demo
          Value: a-new-startup
        Artifacts:
            Type: CODEPIPELINE
        Cache:
              Type: LOCAL
              Modes:
                - LOCAL_DOCKER_LAYER_CACHE
        Environment:
            ComputeType: BUILD_GENERAL1_SMALL
            # NOTE: Using Ubuntu/7.0 image - Docker already installed
            Image: aws/codebuild/standard:7.0
            # Must be on for a container image build - Docker daemon must run as root
            PrivilegedMode: true
            Type: LINUX_CONTAINER
            EnvironmentVariables:
            - Name: ACCOUNTID
              Type: PLAINTEXT
              Value:
                Ref:
                  AWS::AccountId
            - Name: AWS_DEFAULT_REGION
              Type: PLAINTEXT
              Value:
                Ref:
                  AWS::Region
        ServiceRole:
            Fn::GetAtt:
            - BuildRole
            - Arn
        Source:
            BuildSpec: buildspec-build-image.yml
            Type: CODEPIPELINE

  # This project is used to run the tests (by running the testing container image)
  RunTestsBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
        Name: a-new-startup-run-tests
        Tags:
          - Key: demo
            Value: a-new-startup
        Artifacts:
            Type: CODEPIPELINE
        Cache:
              Type: LOCAL
              Modes:
                - LOCAL_DOCKER_LAYER_CACHE
        Environment:
            ComputeType: BUILD_GENERAL1_SMALL
            # NOTE: Using Ubuntu/7.0 image - Docker already installed
            Image: aws/codebuild/standard:7.0            
            # Must be on for a container image build - docker daemon must run as root.
            PrivilegedMode: true
            Type: LINUX_CONTAINER
            EnvironmentVariables:
            - Name: ACCOUNTID
              Type: PLAINTEXT
              Value:
                Ref:
                  AWS::AccountId
            - Name: AWS_DEFAULT_REGION
              Type: PLAINTEXT
              Value:
                Ref:
                  AWS::Region
        ServiceRole:
            Fn::GetAtt:
            - BuildRole
            - Arn
        Source:
            BuildSpec: buildspec-to-test.yml
            Type: CODEPIPELINE


#   ___         _     ___           _          
#  / __|___  __| |___|   \ ___ _ __| |___ _  _ 
# | (__/ _ \/ _` / -_) |) / -_) '_ \ / _ \ || |
#  \___\___/\__,_\___|___/\___| .__/_\___/\_, |
#                             |_|         |__/ 

  Application:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: "a-new-startup"
      ComputePlatform: Server
      Tags:
        - Key: demo
          Value: a-new-startup


  DeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: "a-new-startup"
      Tags:
        - Key: demo
          Value: a-new-startup
      AutoScalingGroups:
      - "a-new-startup"
      DeploymentConfigName: "CodeDeployDefault.OneAtATime"
      # Don't change this.
      # The code uses its DeploymentGroupName to figure out which environment it is (dev/qa/prod)
      # and then retrieves the corresponding parameters (dev table, dev sns , etc.)
      DeploymentGroupName: "dev"
      DeploymentStyle: 
        # There's also "WITH_TRAFFIC_CONTROL": https://docs.aws.amazon.com/codedeploy/latest/userguide/integrations-aws-elastic-load-balancing.html
        # You have to use some scripts to de-register and re-register with the ELB during the lifecycle events.
        # It's a bit too much complication for a simple demo (but would be recommended for real world)
        DeploymentOption: WITHOUT_TRAFFIC_CONTROL
        DeploymentType: IN_PLACE
      Ec2TagFilters:
        - Key: deploymentgroup
          Value: a-new-startup
          Type: KEY_AND_VALUE
      LoadBalancerInfo:
        TargetGroupInfoList:
          - Name: "a-new-startup"
      ServiceRoleArn:
        Fn::GetAtt:
          - CodeDeployRole
          - Arn


#
#  ___  __     __   _  _  ____  _  _   __  ____  ___  _  _ 
# / __)(  )   /  \ / )( \(    \/ )( \ / _\(_  _)/ __)/ )( \
#( (__ / (_/\(  O )) \/ ( ) D (\ /\ //    \ )( ( (__ ) __ (
# \___)\____/ \__/ \____/(____/(_/\_)\_/\_/(__) \___)\_)(_/
# 

  AmazonCloudWatchEventRule:
    Type: 'AWS::Events::Rule'
    Properties:
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - CodeCommit Repository State Change
        resources:
          - !Join 
            - ''
            - - 'arn:aws:codecommit:'
              - !Ref 'AWS::Region'
              - ':'
              - !Ref 'AWS::AccountId'
              - ':'
              - 'a-new-startup'
        detail:
          event:
            - referenceCreated
            - referenceUpdated
          referenceType:
            - branch
          referenceName:
            - main
      Targets:
        - Arn: !Join 
            - ''
            - - 'arn:aws:codepipeline:'
              - !Ref 'AWS::Region'
              - ':'
              - !Ref 'AWS::AccountId'
              - ':'
              - 'a-new-startup'
          RoleArn: !GetAtt 
            - AmazonCloudWatchEventRole
            - Arn
          Id: codepipeline-AppPipeline

#
# Log Group & Metrics Filters
# These scan Log Groups for certain text (and count) and can be used to define an Alarm
#

  # This must be defined so that we can have the MetricFilters further down.
  # The BuildProject output will automatically use this LogGroup.
  BuildLogGroup: 
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: "/aws/codebuild/a-new-startup-build"
      RetentionInDays: 30

  MetricFilterSucceeeded:
    Type: AWS::Logs::MetricFilter
    DependsOn: BuildLogGroup
    Properties: 
      FilterName: A-New-Startup-Builds-Succeeded
      # Gotta be in double quotes 
      FilterPattern: '"UPLOAD_ARTIFACTS State: SUCCEEDED"'
      LogGroupName: "/aws/codebuild/a-new-startup-build"
      MetricTransformations: 
        - 
          MetricValue: "1"
          MetricNamespace: "A-New-Startup/Builds"
          MetricName: "SuccessfulBuilds"
          Unit: Count
            
  MetricFilterFailed:
    Type: AWS::Logs::MetricFilter
    DependsOn: BuildLogGroup
    Properties: 
      FilterName: A-New-Startup-Builds-Failed
      # Gotta be in double quotes 
      FilterPattern: '"UPLOAD_ARTIFACTS State: FAILED"'
      LogGroupName: "/aws/codebuild/a-new-startup-build"
      MetricTransformations: 
        - 
          MetricValue: "1"
          MetricNamespace: "A-New-Startup"
          MetricName: "FailedBuilds"
          Unit: Count
            
#  __   __   _  _ 
# (  ) / _\ ( \/ )
#  )( /    \/ \/ \
# (__)\_/\_/\_)(_/
#
  AmazonCloudWatchEventRole:
      Type: 'AWS::IAM::Role'
      Properties:
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - events.amazonaws.com
              Action: 'sts:AssumeRole'
        Path: /
        Policies:
          - PolicyName: cwe-pipeline-execution
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action: 'codepipeline:StartPipelineExecution'
                  Resource: !Join 
                    - ''
                    - - 'arn:aws:codepipeline:'
                      - !Ref 'AWS::Region'
                      - ':'
                      - !Ref 'AWS::AccountId'
                      - ':'
                      - 'a-new-startup'

  CodePipelineArtifactStoreBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref ArtifactStoreBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource: !Join 
              - ''
              - - !GetAtt 
                  - ArtifactStoreBucket
                  - Arn
                - /*
            Condition:
              Bool:
                'aws:SecureTransport': false
                    
  CodePipelineServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: AWS-CodePipeline-Service-a-new-startup
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'codecommit:CancelUploadArchive'
                  - 'codecommit:GetBranch'
                  - 'codecommit:GetCommit'
                  - 'codecommit:GetUploadArchiveStatus'
                  - 'codecommit:UploadArchive'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'codedeploy:CreateDeployment'
                  - 'codedeploy:GetApplicationRevision'
                  - 'codedeploy:GetDeployment'
                  - 'codedeploy:GetDeploymentConfig'
                  - 'codedeploy:RegisterApplicationRevision'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'codebuild:BatchGetBuilds'
                  - 'codebuild:StartBuild'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'devicefarm:ListProjects'
                  - 'devicefarm:ListDevicePools'
                  - 'devicefarm:GetRun'
                  - 'devicefarm:GetUpload'
                  - 'devicefarm:CreateUpload'
                  - 'devicefarm:ScheduleRun'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                  - 'lambda:ListFunctions'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'iam:PassRole'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'elasticbeanstalk:*'
                  - 'ec2:*'
                  - 'elasticloadbalancing:*'
                  - 'autoscaling:*'
                  - 'cloudwatch:*'
                  - 's3:*'
                  - 'sns:*'
                  - 'cloudformation:*'
                  - 'rds:*'
                  - 'sqs:*'
                  - 'ecs:*'
                Resource: '*'


  BuildRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: CodeBuild-Role-a-new-startup
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'codebuild:*'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                  - 'lambda:ListFunctions'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'iam:PassRole'
                Resource: '*'
                # ECR perms needed to build and push the testing container image
              - Effect: Allow
                Action:
                  - 'ecr:BatchGetImage'
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:CompleteLayerUpload'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:InitiateLayerUpload'
                  - 'ecr:PutImage'
                  - 'ecr:UploadLayerPart'
                  - 'ecr:GetAuthorizationToken'
                Resource: '*'
                # Need to be able to retrieve Outputs from stacks...
              - Effect: Allow
                Action:
                  - 'cloudformation:DescribeStacks'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'cloudwatch:*'
                  - 'logs:CreateLogStream'
                  - 'logs:CreateLogGroup'
                  - 'logs:PutLogEvents'
                  - 's3:*'
                Resource: '*'
                
  CodeDeployRole:
      Type: 'AWS::IAM::Role'
      Properties:
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - codedeploy.amazonaws.com
              Action: 'sts:AssumeRole'
        Path: /
        Policies:
          - PolicyName: codedeploy-role-a-new-startup
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action: 'ec2:*'
                  Resource: !Join 
                    - ''
                    - - '*'
                - Effect: Allow
                  Action: 'autoscaling:*'
                  Resource: !Join 
                    - ''
                    - - '*'

  CFNDeployRole:
      Type: 'AWS::IAM::Role'
      Properties:
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - cloudformation.amazonaws.com
              Action: 'sts:AssumeRole'
        Path: /
        Policies:
          - PolicyName: !Join
              - '-'
              - - !Ref Prefix
                - "cfn-deploy-backend"

            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - 'iam:PassRole'
                    - 'iam:CreateRole'
                    - 'iam:DeleteRole'
                    - 'iam:AttachRolePolicy'
                    - 'iam:DeleteRolePolicy'
                    - 'iam:DetachRolePolicy'
                    - 'iam:PutRolePolicy'
                    - 'iam:GetRole'
                  Resource: !Join 
                    - ''
                    - - '*'
                - Effect: Allow
                  Action:
                    - 'cloudformation:CreateChangeSet'
                    - 'cloudformation:ExecuteChangeSet'
                    - 'cloudformation:DescribeStacks'
                    - 'cloudwatch:*'
                    - 'ecs:*'
                    - 'ec2:CreateSecurityGroup'
                    - 'ec2:DescribeSecurityGroups'
                    - 'ec2:DeleteSecurityGroup'
                    - 'elasticloadbalancing:CreateTargetGroup'
                    - 'elasticloadbalancing:DeleteTargetGroup'
                    - 'elasticloadbalancing:DescribeTargetGroups'
                    - 'elasticloadbalancing:ModifyTargetGroupAttributes'
                    - 'elasticloadbalancing:DescribeListeners'
                    - 'elasticloadbalancing:CreateListener'
                    - 'elasticloadbalancing:DeleteListener'
                    - 'logs:CreateLogGroup'
                    - 'logs:DeleteLogGroup'
                    - 'logs:Describe*'
                    - 'logs:CreateLogStream'
                    - 'logs:PutLogEvents'
                    - 'ec2:AuthorizeSecurityGroupIngress'
                    # TODO: Make more precise
                    - 'dynamodb:*'
                    - 'sqs:*'
                    - 'sns:*'
                    - 'iam:GetPolicy'
                    - 'iam:ListPolicyVersions'
                    - 'iam:CreatePolicy'
                    - 'iam:CreatePolicyVersion'
                    - 'iam:DeletePolicy'
                    - 'iam:DeletePolicyVersion'
                    - 'ssm:PutParameter'
                    - 'ssm:DeleteParameter'
                    - 'ssm:AddTagsToResource'
                  Resource: '*'

                    
Outputs:
  ArtifactStoreBucket:
    Description: Where the build artifacts go.
    Value: !Ref ArtifactStoreBucket
    Export:
      Name: !Join ['-', [!Ref Prefix, 'ArtifactStoreBucket']]
  
  BuildProject:
    Value: !Ref BuildProject
    Export:
      Name: !Join ['-', [!Ref Prefix, 'BuildProject']]
      
  RunTestsBuildProject:    
    Value: !Ref RunTestsBuildProject
    Export:
      Name: !Join ['-', [!Ref Prefix, 'RunTestsBuildProject']]
      
  TestImageBuildProject:
    Value: !Ref TestImageBuildProject
    Export:
      Name: !Join ['-', [!Ref Prefix, 'TestImageBuildProject']]
  
  Application:
    Value: !Ref Application
    Export:
      Name: !Join ['-', [!Ref Prefix, 'Application']]
  
  DeploymentGroup:
    Value: !Ref DeploymentGroup
    Export:
      Name: !Join ['-', [!Ref Prefix, 'DeploymentGroup']]
      
  CodePipelineServiceRole:
    Value: !GetAtt CodePipelineServiceRole.Arn
    Export:
      Name: !Join ['-', [!Ref Prefix, 'CodePipelineServiceRole']]
      
  CFNDeployRole:
    Value: !GetAtt CFNDeployRole.Arn
    Export:
      Name: !Join ['-', [!Ref Prefix, 'CFNDeployRole']]
