AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  a-new-startup : Sets up the frontend layer of the app - An ALB in front of an ASG of Amazon Linux 2 EC2 instances.

Parameters:

  VpcId:
    Type: String
    Description: "The VPC Id where the ALB/ASG/Launch Template should be created"
    
  Subnets:
    Description: Choose which subnets the Application Load Balancer should be deployed to.  Must be Public subnets!
    Type: List<AWS::EC2::Subnet::Id>

  AmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64'
    Description: "Amazon Linux 2023 AMI ID to use - defaults to latest for this region."
    
  InstanceType:
    Type: String
    # t3 have unlimited bursting. This demo works better if it doesn't take forever for all the setup to happen...
    # ... so be careful if you use a smaller size.
    Default: "t3.large"
    AllowedValues: ["t2.micro", "t3.micro", "t2.small", "t3.small", "t3.medium", "t3.large", "t3.xlarge"]
    Description: "Enter instance type to use. Default is t3.large"
  
  IpRangesForAccess:
    Type: CommaDelimitedList
    # Don't leave EC2 IPs open to the Internet
    # This is expected to be a comma separated list of FOUR IPs:
    # Your IP (from where you will demo), and the 3 CodeBuild IP ranges
    # (If you use the test pipeline, CodeBuild needs access to hit the web app for system testing)
    Default: "1.1.1.1/32,2.2.2.2/32,3.3.3.3/32,4.4.4.4/32"

  Prefix:
    Type: String
    Default: "a-new-startup"
    Description: "Used for the unique naming of resources and exports.  You probably should not change this."

#
# Override the defaults for these two parameters if you wish to use:
# 1. A custom domain name (such as app.example.com)
# 2. An HTTPS (443) listener with an ACM certificate
# 
# You must have the Domain already configured in Route 53 as a Hosted Zone.

  DomainName:
    Type: String
    Default: "None"
    Description: "Leave as None to use HTTP/80. If you have a Domain hosted in Route 53, you can specify that here to use HTTPS/443 - a certificate will be used with the ALB. You must also specify the Hosted Zone Id."

  HostedZoneId:
    Type: String
    Default: "None"
    Description: "Leave as None to use HTTP/80.  If you have a Domain hosted in Route 53, you can specify the Hosted Zone ID here. You must also specify DomainName desired."

Conditions:
  
  UseDomainName: !Not
    - !Equals
      - !Ref DomainName
      - 'None'
  UseHostedZoneId: !Not
    - !Equals
      - !Ref HostedZoneId
      - 'None'
      
  # Use a custom domain name if DomainName and HostedZoneId are provided.    
  UseHTTPS: !And
    - !Condition UseDomainName
    - !Condition UseHostedZoneId
    
Resources:

  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: "Security group for a-new-startup application EC2 instances"
      SecurityGroupIngress:

        # NOTE: Same rule repeated 4 times for the 4 IP ranges that you *MUST* 
        # specify : Your IP, and three CodeBuild IP ranges.
        # CodeBuild environments need access to run tests.

        - CidrIp: !Select [0, !Ref IpRangesForAccess]
          FromPort: !If
            - UseHTTPS
            - 443
            - 80
          ToPort: !If
            - UseHTTPS
            - 443
            - 80
          IpProtocol: tcp
          # NodeJS app is listening on port 3000
          # For debugging and demos, we want to demonstrate this without going via the ALB.
          # Which is why we put these in Public subnets ideally - for an easier demo.
        - CidrIp: !Select [0, !Ref IpRangesForAccess]
          FromPort: 3000
          ToPort: 3000
          IpProtocol: tcp

        - CidrIp: !Select [1, !Ref IpRangesForAccess]
          FromPort: !If
            - UseHTTPS
            - 443
            - 80
          ToPort: !If
            - UseHTTPS
            - 443
            - 80
          IpProtocol: tcp
          # NodeJS app is listening on port 3000
          # For debugging and demos, we want to demonstrate this without going via the ALB.
          # Which is why we put these in Public subnets ideally - for an easier demo.
        - CidrIp: !Select [1, !Ref IpRangesForAccess]
          FromPort: 3000
          ToPort: 3000
          IpProtocol: tcp

        - CidrIp: !Select [2, !Ref IpRangesForAccess]
          FromPort: !If
            - UseHTTPS
            - 443
            - 80
          ToPort: !If
            - UseHTTPS
            - 443
            - 80
          IpProtocol: tcp
          # NodeJS app is listening on port 3000
          # For debugging and demos, we want to demonstrate this without going via the ALB.
          # Which is why we put these in Public subnets ideally - for an easier demo.
        - CidrIp: !Select [2, !Ref IpRangesForAccess]
          FromPort: 3000
          ToPort: 3000
          IpProtocol: tcp

        - CidrIp: !Select [3, !Ref IpRangesForAccess]
          FromPort: !If
            - UseHTTPS
            - 443
            - 80
          ToPort: !If
            - UseHTTPS
            - 443
            - 80
          IpProtocol: tcp
          # NodeJS app is listening on port 3000
          # For debugging and demos, we want to demonstrate this without going via the ALB.
          # Which is why we put these in Public subnets ideally - for an easier demo.
        - CidrIp: !Select [3, !Ref IpRangesForAccess]
          FromPort: 3000
          ToPort: 3000
          IpProtocol: tcp

      VpcId: !Ref VpcId
  
  # So the ALB can hit the EC2 instances on port 3000 (NodeJS)
  SecurityGroupIngress:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      Description: "So the ALB can reach the NodeJs listening on 3000"
      GroupId: !GetAtt SecurityGroup.GroupId
      SourceSecurityGroupId: !GetAtt SecurityGroup.GroupId
      FromPort: 3000
      ToPort: 3000
      IpProtocol: tcp
      
  #
  #
  # There will be a default Outbound Allow rule automatically, we don't need to specify that.
  #
  #
  
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      # No Name specified so we get a dynamic name.
      Roles:
        - !Ref InstanceProfileRole

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: a-new-startup
      LaunchTemplateData:
        Monitoring:
          Enabled: true
        IamInstanceProfile:
          Arn: !GetAtt
            - InstanceProfile
            - Arn
        ImageId: !Ref AmiId
        InstanceType: !Ref InstanceType
        # IMDSv2 - https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html
        MetadataOptions:
          HttpEndpoint: enabled
          HttpTokens: required
        SecurityGroupIds:
          - !Ref SecurityGroup
        # We *might* use these tags later to put these instance in the DeploymentGroup
        # We also have the option of using the ASG instead
        TagSpecifications:
        - ResourceType: instance
          Tags:
          - Key: deploymentgroup
            Value: a-new-startup
          - Key: Name
            Value: a-new-startup
          - Key: demo
            Value: a-new-startup
        UserData:
          # Run this UserData to install the CodeDeploy Agent.  
          Fn::Base64: !Sub | 
            #!/bin/bash -xe
            #
            # Install pre-requisites for CodeDeploy, and other necessary things
            # October 2023:
            # I have found on AL2023 that any "dnf install" command is prone to fail randomly with:
            # [Errno 2] No such file or directory: '/var/cache/dnf/amazonlinux-1a4296c84a720383/....
            # Therefore, we use this simple technique when installing all required packages.
            # The while loop will execute repeatedly until a success happens
            # (If the machine never gets healthy the ELB Health Check will terminate it)
            #
            while ! dnf install -y wget; do dnf clean packages; sleep 15; done
            while ! dnf install -y jq; do dnf clean packages; sleep 15; done
            while ! dnf install -y stress; do dnf clean packages; sleep 15; done
            #
            # Ruby needed for CodeDeploy
            while ! dnf install -y ruby; do dnf clean packages; sleep 15; done
            #
            # Get IMDSv2 token
            TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 600")
            # Figure out what region we are running in
            REGION=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -s 169.254.169.254/latest/dynamic/instance-identity/document | jq -r ".region")
            #
            # Install NodeJS 18
            #
            # Needed as per (2024-02-05): https://github.com/nodesource/distributions/issues/1740
            curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
            # while ! dnf install https://rpm.nodesource.com/pub_18.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y; do dnf clean packages; sleep 15; done
            while ! dnf install -y nodejs; do dnf clean packages; sleep 15; done
            npm -v
            node -v
            #
            # Install XRay - latest 3.x release
            #
            curl https://s3.$REGION.amazonaws.com/aws-xray-assets.$REGION/xray-daemon/aws-xray-daemon-3.x.rpm -o /home/ec2-user/xray.rpm
            while ! dnf install -y /home/ec2-user/xray.rpm; do dnf clean packages; sleep 15; done
            systemctl enable xray
            systemctl status xray
            #
            # Install CloudWatch agent - You can use SSM document later to configure (if you want to)
            while ! dnf install -y amazon-cloudwatch-agent; do dnf clean packages; sleep 15; done
            # CloudWatch agent is installed, but not running. Set the config before you start it.
            # See 08-configure-cloudwatch.sh
            #
            # Install CodeDeploy Agent
            # We'll use this to install our app later when the CI/CD pipeline runs.
            # Install this last to minimize conflicts with packages being installed by UserData while CodeDeploy is trying also
            #
            cd /home/ec2-user
            URL="https://aws-codedeploy-$REGION.s3.$REGION.amazonaws.com/latest/install"
            wget $URL
            chmod +x ./install
            ./install auto
            service codedeploy-agent start
            service codedeploy-agent status

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: "a-new-startup"
      VPCZoneIdentifier: !Ref Subnets
      MinSize: 2
      DesiredCapacity: 2
      MaxSize: 8 
      # Will use both EC2 and ELB health checks
      # Please note that this can cause issues if your instances are being patched as soon as they boot.
      # The reboot that SSM Patching does will interrupt the CodeDeploy process
      # and the instances will constantly churn as they will be terminated and replaced
      # ... only for the same thing to happen over and over.
      HealthCheckType: ELB
      # When an instance first becomes "InService" give it a bit to get going...
      # Consider we are doing "OneAtATime" Deployment, if you have a lot of instances
      # it takes MINUTES to get through them all...
      HealthCheckGracePeriod: 600
      TargetGroupARNs:
        - !Ref DefaultTargetGroup
      LaunchTemplate:
        LaunchTemplateName: "a-new-startup"
        # Use the latest version available at the time this is being created. (So - version 1 always)
        # There's no "latest" capability via CloudFormation
        # If you update the stack later it would update the version used.
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
  
  # Default scaling policy - 50% CPU utilization
  ScalingPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: 50

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      Name: "a-new-startup" 
      Scheme: internet-facing
      SecurityGroups: 
        - !Ref SecurityGroup
      Subnets: !Ref Subnets
      Type: application
      LoadBalancerAttributes:
      - Key: access_logs.s3.enabled
        Value: true
      - Key: access_logs.s3.bucket
        Value: !ImportValue "a-new-startup-LoggingBucket"
      - Key: access_logs.s3.prefix
        Value: !Ref Prefix
      Tags:
      - Key: Name
        Value: a-new-startup-ec2
      - Key: demo
        Value: a-new-startup
           
  # This is only created if we are using HTTPS
  # This is an ACM Certificate for the ALB's 443 Listener
  Certificate: 
    Type: "AWS::CertificateManager::Certificate"
    Condition: UseHTTPS
    Properties: 
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
            - DomainName: !Ref DomainName
              HostedZoneId: !Ref HostedZoneId
  
  # This is only created if we are using HTTPS
  # This is the DNS CNAME record that will point the domain name to the ALB
  DNS:
    Type: AWS::Route53::RecordSetGroup
    Condition: UseHTTPS
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
      # NOTE: Needs the "." on the end.
      - Name: !Sub '${DomainName}.'
        Type: CNAME
        TTL: '60'
        ResourceRecords:
        - !GetAtt ApplicationLoadBalancer.DNSName
  #    
  # Setup the listener - either on HTTP/80 
  # OR
  # HTTPS/443 with a Certificate 
  #
  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: !If
        - UseHTTPS
        - 443
        - 80
      Protocol: !If
        - UseHTTPS
        - HTTPS
        - HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref DefaultTargetGroup
      Certificates: 
        !If
        - UseHTTPS  
        - 
          # Needs to be nested like this. It's a LIST
          - CertificateArn: !Ref Certificate
        - !Ref AWS::NoValue

  DefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: 3000
      Protocol: HTTP
      # Check health every 30 seconds
      HealthCheckIntervalSeconds: 30
      HealthyThresholdCount: 2
      # Set this high because otherwise the initial deployment will get bogged down due to
      # servers constantly being terminated because they are unhealthy.
      # 10 is the max.
      # (The Load Balancer will be hitting Port 3000 expecting something to be there, but the first build must complete before the install will happen)
      UnhealthyThresholdCount: 10
      # Set de-regisration really low - makes for faster demos and debugging
      # Set this higher in real-life
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 10
  
  InstanceProfileRole:
    Type: AWS::IAM::Role
    # The Role to be used by the EC2 instance - includes application permissions and SSM
    Properties:
      # Static name for simplicity - can only install once per region (which is enough)
      RoleName: !Sub 'a-new-startup-InstanceProfileRole-${AWS::Region}'
      Description: Role for EC2 Instance Profile for A-New-Startup
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        # Use this Managed Policy so we can use SSM - Session Manager, Patch Manager, etc.
        - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
        # CloudWatch Agent policy 
        - "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
        # Also will add the app permissions via the policy in an earlier stack.
        - !ImportValue "a-new-startup-AppManagedPolicy"

                    
Outputs:

  Protocol:
    Description: Indicates whether or not HTTPS was used
    Value: !If
      - UseHTTPS
      - 'https'
      - 'http'
    Export:
      Name: !Join ['-', [!Ref Prefix, 'Protocol']]

  DomainName:
    Description: If using a custom domain, this is the Parameter that was input. We make it a stack output so it's convenient for testing later.
    Value: !Ref DomainName
    Export:
      Name: !Join ['-', [!Ref Prefix, 'DomainName']] 

  ALBDNS:
    Description: DNS Of the ALB - pull this up in the browser to see the application.
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Join ['-', [!Ref Prefix, 'ALBDNS']]

  ALBARN:
    Description: The ALB ARN - use this with a waiter to check and see if it is provisioned yet.
    Value: !Ref ApplicationLoadBalancer
    Export:
      Name: !Join ['-', [!Ref Prefix, 'ALBARN']]
  
  InstanceProfileRoleName:
    Value: !Ref InstanceProfileRole
    Export:
      Name: !Join ['-', [!Ref Prefix, 'pipeline-InstanceProfileRoleName']]
