AWSTemplateFormatVersion: '2010-09-09'
Description: A-New-Startup app - CodeCommit repos and ECR Repos used by the CI/CD Pipeline

Parameters:

  CodeBucketName:
    Type: String
    Description: "Name of s3 bucket containing the a-new-startup.zip source code - to initialize the repo."

Mappings:

  RegionalConfigs:
    # Accounts needed to grant access for ELB access logging as per: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/enable-access-logging.html
    us-east-1:
      ELBAccountId: '127311923021'
    us-east-2:
      ELBAccountId: '033677994240'
    us-west-2:
      ELBAccountId: '797873946194'
    ca-central-1:
      ELBAccountId: '985666609251'


Resources:

  CodeCommitRepo:
    Type: AWS::CodeCommit::Repository
    Properties: 
      Code: 
        S3:
          # We initialize the CodeCommit repo contents from this zip.
          # This ONLY WORKS ON INITIAL CREATE.  You cannot update repo contents through CF.
          Bucket: !Ref CodeBucketName
          Key: a-new-startup.zip
      RepositoryDescription: "The A-New-Startup application code - used in a CI/CD pipeline"
      RepositoryName: "a-new-startup"
      Tags:
        - Key: demo
          Value: a-new-startup

  #
  # Everything below here is for the testing code
  # Which is Python and turned into a container image
  #

  BaseImageRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "a-new-startup-test-base-image"
      Tags:
        - Key: demo
          Value: a-new-startup
            
  TestingImageRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "a-new-startup-testing-image"
      Tags:
        - Key: demo
          Value: a-new-startup

  TestingCodeCommitRepo:
    Type: AWS::CodeCommit::Repository
    Properties: 
      Code: 
        S3:
          # We initialize the CodeCommit repo contents from this zip.
          # This ONLY WORKS ON INITIAL CREATE.  You cannot update repo contents through CF.
          Bucket: !Ref CodeBucketName
          Key: a-new-startup-ui-tests.zip
      RepositoryDescription: "The A-New-Startup testing code - used in a CI/CD pipeline"
      RepositoryName: "a-new-startup-testing-image"
      Tags:
        - Key: demo
          Value: a-new-startup

  # ALB will use this for Access Logs
  LoggingBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      Tags:
        - Key: demo
          Value: a-new-startup
          
  # Enable ELB access logs as per: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/enable-access-logging.html
  LoggingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref LoggingBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:PutObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref LoggingBucket
                - '/*'
            Principal:
              AWS: !Join
                - ''
                - - 'arn:aws:iam::'
                  - !FindInMap [ "RegionalConfigs", !Ref "AWS::Region", "ELBAccountId"]
                  - ':root'

Outputs:
  LoggingBucket:
    Description: Where the alb access logs go.
    Value: !Ref LoggingBucket
    Export:
      Name: !Join ['-', ['a-new-startup', 'LoggingBucket']]
