version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - PREFIX=zzz-test-a-new-startup
      
      # Gotta install AWS CLI v2
      - pip3 uninstall awscli -y
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip 1> /dev/null
      - ./aws/install
      - aws --version
      
      - curl --version

  pre_build:
    commands:
    
      # Grab some Stack Exports
      - BUCKET_NAME=$(aws cloudformation list-exports --query "Exports[?Name=='$PREFIX-CodeBucket'].Value" --output text)
      - echo "BUCKET_NAME=$BUCKET_NAME."
      - PUBLIC_SUBNETS=$(aws cloudformation list-exports --query "Exports[?Name=='$PREFIX-PublicSubnetIds'].Value" --output text)
      - echo "PUBLIC_SUBNETS=$PUBLIC_SUBNETS."
      
      # Get Private Key - from SecretsManager. It MUST be in a Secret named as "github-pipeline-private-key-1"
      - KEY_NAME=github-pipeline-private-key-1
      - SECRET_ARN=$(aws secretsmanager describe-secret --secret-id $KEY_NAME --query "ARN" --output text)
      
      # Retrieve that value, decode from base64, and write it to ~/.ssh
      - mkdir -p ~/.ssh
      - aws secretsmanager get-secret-value --secret-id "$SECRET_ARN" --query "SecretString" --output text | jq -r '.privatekeybase64' | base64 -d > ~/.ssh/github_pipeline
      
      # Update the ~/.ssh/config so we use it automatically when working with Github.
      - printf '%s\n%s\n' "Host github.com" "IdentityFile ~/.ssh/github_pipeline" >> ~/.ssh/config
      - cat ~/.ssh/config
      - chmod 600 ~/.ssh/github_pipeline
      
  build:
    commands:
      - ./install.sh "$BUCKET_NAME" "$PUBLIC_SUBNETS"
      
      # Wait until ALB Provisioned
      - ALB_ARN=$(aws cloudformation list-exports --query "Exports[?Name=='a-new-startup-ALBARN'].Value" --output text)
      - echo "ALB_ARN=$ALB_ARN."
      - aws elbv2 wait load-balancer-available --load-balancer-arns $ALB_ARN 
      - ALB_DNS=$(aws cloudformation list-exports --query "Exports[?Name=='a-new-startup-ALBDNS'].Value" --output text)
      - echo "ALB_DNS=$ALB_DNS."
      # NOTE: http://
      - curl "http://$ALB_DNS" >> report.txt
      
      # Now, add test stage - this includes a containerized UI level test
      - ./06-add-test-stage.sh

      # Release latest change
      - aws codepipeline start-pipeline-execution --name "a-new-startup"
      - sleep 15
      
      # Wait for the build pipeline to complete.
      # There's 3 Stages in the pipeline, all have to be completed successfully before we move on
      # There is no wait/waiter for codepipeline, unfortunately
      - NUM_STAGES=3
      - SUCCESS_COUNT=0
      - ATTEMPTS=0
      # Check up to 40 times (10 minutes, because we sleep 15s in between)
      - MAX=40 
      - while [ $SUCCESS_COUNT -lt $NUM_STAGES ] && [ $ATTEMPTS -lt $MAX ]
      - do
      - sleep 15
      - SUCCESS_COUNT=$(aws codepipeline get-pipeline-state --name "a-new-startup" --query "stageStates[].latestExecution.status" | grep Succeeded | wc -l)
      - ATTEMPTS=ATTEMPTS+1
      - echo "Number of Successul stages=$SUCCESS_COUNT (Waiting for $NUM_STAGES)... ($ATTEMPTS of $MAX)..."
      - done
      # If we maxed out, fail the build project (non zero exit)
      - if [[ $ATTEMPTS -eq $MAX ]]; then
      - exit 5  
      - fi

      # Wait until ALB Provisioned
      - ALB_ARN=$(aws cloudformation list-exports --query "Exports[?Name=='a-new-startup-ALBARN'].Value" --output text)
      - echo "ALB_ARN=$ALB_ARN."
      - aws elbv2 wait load-balancer-available --load-balancer-arns $ALB_ARN 
      - ALB_DNS=$(aws cloudformation list-exports --query "Exports[?Name=='a-new-startup-ALBDNS'].Value" --output text)
      - echo "ALB_DNS=$ALB_DNS."
      # NOTE: http://
      - curl "http://$ALB_DNS" >> report.txt

      # Now, make it the full pipeline. This pipeline will also setup the backend/infra.
      - ./07-full-pipeline.sh
      
      # Release latest change
      - aws codepipeline start-pipeline-execution --name "a-new-startup"
      - sleep 15
      
      # Wait for the build pipeline to complete.
      # There's 4 Stages in this version of the pipeline, all have to be completed successfully before we move on
      # There is no wait/waiter for codepipeline, unfortunately
      - NUM_STAGES=4
      - SUCCESS_COUNT=0
      - ATTEMPTS=0
      # Check up to 40 times (10 minutes, because we sleep 15s in between)
      - MAX=40 
      - while [ $SUCCESS_COUNT -lt $NUM_STAGES ] && [ $ATTEMPTS -lt $MAX ]
      - do
      - sleep 15
      - SUCCESS_COUNT=$(aws codepipeline get-pipeline-state --name "a-new-startup" --query "stageStates[].latestExecution.status" | grep Succeeded | wc -l)
      - ATTEMPTS=ATTEMPTS+1
      - echo "Number of Successul stages=$SUCCESS_COUNT (Waiting for $NUM_STAGES)... ($ATTEMPTS of $MAX)..."
      - done
      # If we maxed out, fail the build project (non zero exit)
      - if [[ $ATTEMPTS -eq $MAX ]]; then
      - exit 5  
      - fi
      
      # Wait until ALB Provisioned
      - ALB_ARN=$(aws cloudformation list-exports --query "Exports[?Name=='a-new-startup-ALBARN'].Value" --output text)
      - echo "ALB_ARN=$ALB_ARN."
      - aws elbv2 wait load-balancer-available --load-balancer-arns $ALB_ARN 
      - ALB_DNS=$(aws cloudformation list-exports --query "Exports[?Name=='a-new-startup-ALBDNS'].Value" --output text)
      - echo "ALB_DNS=$ALB_DNS."
      # NOTE: http://
      - curl "http://$ALB_DNS" >> report.txt
      
      
  post_build:
    commands:
    
      - ALB_DNS=$(aws cloudformation list-exports --query "Exports[?Name=='a-new-startup-ALBDNS'].Value" --output text)
      - echo "ALB_DNS=$ALB_DNS."
      # NOTE: http://
      - curl "http://$ALB_DNS" >> report.txt

artifacts:
  files:
    - report.txt 
