version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - PREFIX=zzz-test-a-new-startup
      - echo "install" >> report.txt

  pre_build:
    commands:
      - BUCKET_NAME=$(aws cloudformation list-exports --query "Exports[?Name=='$PREFIX-CodeBucket'].Value" --output text)
      - echo "BUCKET_NAME=$BUCKET_NAME."
      - PUBLIC_SUBNETS=$(aws cloudformation list-exports --query "Exports[?Name=='$PREFIX-PublicSubnetIds'].Value" --output text)
      - echo "PUBLIC_SUBNETS=$PUBLIC_SUBNETS."
  build:
    commands:
      - ./install.sh "$BUCKET_NAME" "$PUBLIC_SUBNETS"

artifacts:
  files:
    - report.txt 
