version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - PREFIX=zzz-test-a-new-startup
      - echo "install" >> report.txt

  pre_build:
    commands:
      - BUCKET_NAME=$(aws cloudformation list-exports --query "Exports[?Name=='$PREFIX-CodeBucket'].Value" --output text)
      - echo "BUCKET_NAME=$BUCKET_NAME."
      - echo "pre_build" >> report.txt
  build:
    commands:
      - echo "build" >> report.txt


artifacts:
  files:
    - report.txt 
